// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDadsBYFqVxjefmc4T3cQg6HNC5K3w5n6s',
    appId: '1:104508160337:web:8808243df5daad5d067b70',
    messagingSenderId: '104508160337',
    projectId: 'homehub-b1065',
    authDomain: 'homehub-b1065.firebaseapp.com',
    storageBucket: 'homehub-b1065.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyniZoDHr2UdwZHi9c0FEecFpsMLGaSi8',
    appId: '1:104508160337:android:984c7fa50b605c6f067b70',
    messagingSenderId: '104508160337',
    projectId: 'homehub-b1065',
    storageBucket: 'homehub-b1065.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSIvo2s9E7RJavfFsPnKybk-VP_ewoAhQ',
    appId: '1:104508160337:ios:1ed062f193caaf8c067b70',
    messagingSenderId: '104508160337',
    projectId: 'homehub-b1065',
    storageBucket: 'homehub-b1065.firebasestorage.app',
    iosBundleId: 'com.example.homehub',
  );
}
